In [1]:
(5,7)

(5, 7)

In [2]:
5,7

(5, 7)

In [3]:
(5, )

(5,)

In [4]:
list_a=[1,3,5,7,9]
list_b=[3,5,6,7,9]
list_a+list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [5]:
import numpy as np
array_a=np.array([1,3,5,7,9])
array_b=np.array([3,5,6,7,9])
type(array_a)
array_a+array_b

array([ 4,  8, 11, 14, 18])

In [6]:
import numpy as np
l=[[1,2,3],[2,3,4]]
array=np.array(l)
array.ndim,array.shape,array.size,array.dtype

(2, (2, 3), 6, dtype('int64'))

In [7]:
import numpy as np
np.random.randn(10,5)

array([[ 0.56304599,  0.08444436, -0.62186184, -0.56392452,  0.06145906],
       [-0.30210458, -0.59608062, -0.37769209, -1.18700309,  0.36888571],
       [-1.31102237, -0.14001234,  1.28395823, -0.45737487, -0.10581767],
       [-0.11373655,  0.63937533,  0.49421382,  0.10344107, -0.08993887],
       [ 1.56212772, -0.22879682,  1.12210595,  1.58245655,  0.20262595],
       [ 0.7582223 , -1.48937209,  0.92188499, -0.92441371,  0.03323024],
       [ 0.99617707, -0.90199626, -0.4469326 ,  0.22455071, -0.85548376],
       [ 0.36831126,  1.77660678, -1.65457681, -0.19312282,  0.51241218],
       [ 0.44076387,  0.4221607 ,  0.78029717, -1.2080913 , -1.21379195],
       [-0.46559136,  0.63697632, -0.59459461, -0.69660072, -1.46244831]])

In [11]:
#50位學生 每位有5個分數
sc=np.random.randint(50,101,size=(50,5))
sc

array([[ 96,  51,  85,  90,  80],
       [ 77, 100,  57,  61,  77],
       [ 78,  51,  69,  66,  95],
       [ 54,  75,  65,  58,  62],
       [ 99,  96,  57,  67,  80],
       [ 75,  70,  58,  82,  58],
       [ 93,  92,  95,  92,  88],
       [ 51,  71,  85,  53,  80],
       [ 88,  62,  54,  67, 100],
       [ 68,  80,  89,  71,  98],
       [ 93,  98,  79,  75,  56],
       [ 98,  63,  76,  59,  54],
       [ 64,  74,  62,  53,  64],
       [ 89,  83,  70,  98,  51],
       [ 83,  75,  52,  90,  86],
       [ 50,  91,  77,  57,  66],
       [ 66,  96,  92,  56,  71],
       [ 70,  59,  98,  92,  78],
       [ 89,  67,  54,  66,  50],
       [ 76,  64,  56,  66,  71],
       [ 92,  68,  73, 100,  62],
       [ 51,  75,  50,  71,  81],
       [ 75,  74,  83,  94,  80],
       [ 62,  85,  80,  92,  92],
       [ 76,  80,  79,  54,  64],
       [ 52,  57,  55,  82,  86],
       [ 65,  80,  78, 100,  57],
       [ 71,  69,  53,  73,  91],
       [ 84,  73,  80,  54, 100],
       [ 76,  

In [12]:
#第一個學生
sc[0,:]
#前五個學生
sc[:5,:]
#最後五個學生
sc[-5:,:]

array([[ 78,  95,  79,  71,  95],
       [ 77,  57,  69,  86,  63],
       [ 77,  75,  65, 100,  82],
       [ 89,  53,  61,  53,  59],
       [ 60,  87,  56,  92,  74]])

In [13]:
#全班第一科的分數
sc[:,0]

array([96, 77, 78, 54, 99, 75, 93, 51, 88, 68, 93, 98, 64, 89, 83, 50, 66,
       70, 89, 76, 92, 51, 75, 62, 76, 52, 65, 71, 84, 76, 61, 96, 53, 83,
       87, 94, 93, 73, 61, 74, 85, 93, 84, 84, 70, 78, 77, 77, 89, 60])

In [14]:
#全班第2科的分數
sc[:,1]

array([ 51, 100,  51,  75,  96,  70,  92,  71,  62,  80,  98,  63,  74,
        83,  75,  91,  96,  59,  67,  64,  68,  75,  74,  85,  80,  57,
        80,  69,  73,  89,  79,  80,  88,  55,  55,  53,  50,  76,  73,
        94,  51,  89,  53,  92,  81,  95,  57,  75,  53,  87])

In [15]:
#每位學生的總分
total=sc[:,0]+sc[:,1]+sc[:,2]+sc[:,3]+sc[:,4]
total

array([402, 372, 359, 314, 399, 343, 460, 340, 371, 406, 401, 350, 317,
       391, 386, 341, 381, 397, 326, 333, 395, 328, 406, 411, 353, 332,
       380, 357, 391, 436, 371, 395, 335, 354, 394, 377, 396, 354, 344,
       379, 396, 402, 337, 414, 368, 418, 352, 399, 315, 369])

In [16]:
#使用統計的方法
#每位學生總分
np.sum(sc,axis=1)

array([402, 372, 359, 314, 399, 343, 460, 340, 371, 406, 401, 350, 317,
       391, 386, 341, 381, 397, 326, 333, 395, 328, 406, 411, 353, 332,
       380, 357, 391, 436, 371, 395, 335, 354, 394, 377, 396, 354, 344,
       379, 396, 402, 337, 414, 368, 418, 352, 399, 315, 369])

In [17]:
#每位學生平均
np.mean(sc,axis=1)

array([80.4, 74.4, 71.8, 62.8, 79.8, 68.6, 92. , 68. , 74.2, 81.2, 80.2,
       70. , 63.4, 78.2, 77.2, 68.2, 76.2, 79.4, 65.2, 66.6, 79. , 65.6,
       81.2, 82.2, 70.6, 66.4, 76. , 71.4, 78.2, 87.2, 74.2, 79. , 67. ,
       70.8, 78.8, 75.4, 79.2, 70.8, 68.8, 75.8, 79.2, 80.4, 67.4, 82.8,
       73.6, 83.6, 70.4, 79.8, 63. , 73.8])