In [1]:
(5,7)

(5, 7)

In [2]:
5,7

(5, 7)

In [3]:
(5, )

(5,)

In [4]:
list_a=[1,3,5,7,9]
list_b=[3,5,6,7,9]
list_a+list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [5]:
import numpy as np
array_a=np.array([1,3,5,7,9])
array_b=np.array([3,5,6,7,9])
type(array_a)
array_a+array_b

array([ 4,  8, 11, 14, 18])

In [6]:
import numpy as np
l=[[1,2,3],[2,3,4]]
array=np.array(l)
array.ndim,array.shape,array.size,array.dtype

(2, (2, 3), 6, dtype('int64'))

In [7]:
import numpy as np
np.random.randn(10,5)

array([[ 0.56304599,  0.08444436, -0.62186184, -0.56392452,  0.06145906],
       [-0.30210458, -0.59608062, -0.37769209, -1.18700309,  0.36888571],
       [-1.31102237, -0.14001234,  1.28395823, -0.45737487, -0.10581767],
       [-0.11373655,  0.63937533,  0.49421382,  0.10344107, -0.08993887],
       [ 1.56212772, -0.22879682,  1.12210595,  1.58245655,  0.20262595],
       [ 0.7582223 , -1.48937209,  0.92188499, -0.92441371,  0.03323024],
       [ 0.99617707, -0.90199626, -0.4469326 ,  0.22455071, -0.85548376],
       [ 0.36831126,  1.77660678, -1.65457681, -0.19312282,  0.51241218],
       [ 0.44076387,  0.4221607 ,  0.78029717, -1.2080913 , -1.21379195],
       [-0.46559136,  0.63697632, -0.59459461, -0.69660072, -1.46244831]])

In [11]:
#50位學生 每位有5個分數
sc=np.random.randint(50,101,size=(50,5))
sc

array([[ 96,  51,  85,  90,  80],
       [ 77, 100,  57,  61,  77],
       [ 78,  51,  69,  66,  95],
       [ 54,  75,  65,  58,  62],
       [ 99,  96,  57,  67,  80],
       [ 75,  70,  58,  82,  58],
       [ 93,  92,  95,  92,  88],
       [ 51,  71,  85,  53,  80],
       [ 88,  62,  54,  67, 100],
       [ 68,  80,  89,  71,  98],
       [ 93,  98,  79,  75,  56],
       [ 98,  63,  76,  59,  54],
       [ 64,  74,  62,  53,  64],
       [ 89,  83,  70,  98,  51],
       [ 83,  75,  52,  90,  86],
       [ 50,  91,  77,  57,  66],
       [ 66,  96,  92,  56,  71],
       [ 70,  59,  98,  92,  78],
       [ 89,  67,  54,  66,  50],
       [ 76,  64,  56,  66,  71],
       [ 92,  68,  73, 100,  62],
       [ 51,  75,  50,  71,  81],
       [ 75,  74,  83,  94,  80],
       [ 62,  85,  80,  92,  92],
       [ 76,  80,  79,  54,  64],
       [ 52,  57,  55,  82,  86],
       [ 65,  80,  78, 100,  57],
       [ 71,  69,  53,  73,  91],
       [ 84,  73,  80,  54, 100],
       [ 76,  